### ISSUE TITLE
integer_cooperative_matrix does not work

### ISSUE THREAD

**Issue by rcavicchioli** [jeffbolznv/vk_cooperative_matrix_perf#1]
I was trying to benchmark the performance of an NVIDIA TITAN RTX , nvidia driver version 440.100 (on Ubuntu 18.04.01)
with the code in this repo.

the function:
vkGetPhysicalDeviceCooperativeMatrixPropertiesNV
doesn't seem to store in the cooperativeMatrixProperties vector any integer element
for the AType field of the VkCooperativeMatrixPropertiesNV struct.

More specifically, if after context initialization and before any benchmark I write:

printf("What I am going to do \n");
for (uint32_t tt = 0; tt < TT_COUNT; ++tt) {
for (uint32_t i = 0; i < numCooperativeMatrixProperties; ++i) {
VkCooperativeMatrixPropertiesNV *cooperativeMatrixProps = &cooperativeMatrixProperties[i];
printf("\ncooperativeMatrixProps = %dx%dx%d A = %s B = %s C = %s D = %s scope = %s\n",
cooperativeMatrixProps->MSize,
cooperativeMatrixProps->NSize,
cooperativeMatrixProps->KSize,
componentTypeInfo[cooperativeMatrixProps->AType].typeName,
componentTypeInfo[cooperativeMatrixProps->BType].typeName,
componentTypeInfo[cooperativeMatrixProps->CType].typeName,
componentTypeInfo[cooperativeMatrixProps->DType].typeName,
scopeString[cooperativeMatrixProps->scope]);
}
}

I obtain the following output:

What I am going to do

cooperativeMatrixProps = 16x8x16 A = float16_t B = float16_t C = float16_t D = float16_t scope = subgroup
cooperativeMatrixProps = 16x8x8 A = float16_t B = float16_t C = float16_t D = float16_t scope = subgroup
cooperativeMatrixProps = 16x8x16 A = float16_t B = float16_t C = float32_t D = float32_t scope = subgroup
cooperativeMatrixProps = 16x8x8 A = float16_t B = float16_t C = float32_t D = float32_t scope = subgroup
cooperativeMatrixProps = 16x8x16 A = float16_t B = float16_t C = float16_t D = float16_t scope = subgroup
cooperativeMatrixProps = 16x8x8 A = float16_t B = float16_t C = float16_t D = float16_t scope = subgroup
cooperativeMatrixProps = 16x8x16 A = float16_t B = float16_t C = float32_t D = float32_t scope = subgroup
cooperativeMatrixProps = 16x8x8 A = float16_t B = float16_t C = float32_t D = float32_t scope = subgroup

No integer types for A.
Benchmarks are only performed on float types.
I did not modified nor recompiled the shaders.

**Comment by jeffbolznv** [comment]
I think the UDA drivers for R440 don't support the integer types. Can you try either the R445 drivers, or the developer driver at https://developer.nvidia.com/vulkan-driver?

**Comment by rcavicchioli** [comment]
From the official NVIDIA page it states this:
August 29th, 2019 - Windows 436.20, Linux 435.19.02

New:
Rebased Vulkan beta driver features to the latest 436.15 (Windows) and 435.17 (Linux) general release drivers
8-bit integer support added to VK_NV_cooperative_matrix

So using 440 in linux should be enough, right?

**Comment by jeffbolznv** [comment]
The developer drivers come from a different branch than the web drivers, so the numbers aren't really comparable. The normal web drivers I don't think support the integer types until r445.
